# -*- mode: makefile -*- 

######################################################################
# Directories
######################################################################
#
# Installation directory prefix
#
# binaries will be looked in $(XXX_PREFIX)/bin,
# C include files in $(XXX_PREFIX)/include,
# C libraries and OCaml object files and libraries
# in $(PREFIX_INSTALL)/lib

# Home of CELIA set by configuration file

# Where to find/install APRON
#
APRON_CCINC= /usr/include/apron
APRON_OCINC= /usr/lib64/ocaml/apron
APRON_LIBS = /usr/lib64/ocaml/apron

# Where to find PPL ($(PPL_PREFIX)/include, $(PPL_PREFIX)/lib
#
PPL_PREFIX = /usr

# Where to find GMP
#
GMP_PREFIX = /usr

# Where to find MPFR
# (needed if HAS_MPFR=1)
MPFR_PREFIX = /usr

# Where to find MPFR
# Where to find OCAML ($(CAML_PREFIX)/bin, $(CAML_PREFIX)/lib/ocaml, ...)
#
CAML_PREFIX = /usr

# Where to find CAMLIDL
#
CAMLIDL_PREFIX = /usr

######################################################################
# Tools and Flags
######################################################################

# C compiler
CC = gcc

# C compilation flags 
CFLAGS = \
-Wcast-qual -Wswitch -Werror-implicit-function-declaration \
-Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes \
-Wno-unused \
-std=c99 -U__STRICT_ANSI__ \
-fPIC -O0 -DNDEBUG -DNDEBUG1 -DNDEBUG2

# C compilation flags in debug (or profile) mode
CFLAGS_DEBUG = \
-Wcast-qual -Wswitch -Werror-implicit-function-declaration \
-Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes \
-Wno-unused \
-std=c99  -U__STRICT_ANSI__ \
-fPIC -g -O0 -UNDEBUG -UNDEBUG1 -UNDEBUG2

# Examples of CFLAGS
# CFLAGS = -Wswitch -Werror-implicit-function-declaration -Wall -std=c99	\
#	   -O3 -DNDEBUG \
#          -march=pentium-m -mtune=pentium-m -pipe -mmmx -msse -msse2 \
#	   -mfpmath=sse -ftracer -funit-at-a-time -funroll-loops -fmove-all-movables

# C++ compiler
CXX = g++
# C++ compilation flags
CXXFLAGS = \
-Wcast-qual -Wswitch \
-Wall -Wextra -Wundef -Wcast-align \
-Wno-unused \
-O3 -DNDEBUG
# C++ compilation flags in debug (or profile) mode
CXXFLAGS_DEBUG = \
-Wcast-qual -Wswitch \
-Wall -Wextra -Wundef -Wcast-align \
-Wno-unused \
-g -O0 -UNDEBUG

AR = ar
RANLIB = ranlib
SED = sed
M4 = m4
INSTALL = install
INSTALLd = install -d

OCAMLC = $(CAML_PREFIX)/bin/ocamlc.opt
OCAMLOPT = $(CAML_PREFIX)/bin/ocamlopt.opt

# ocamlc compilation flags
OCAMLFLAGS = -g
# ocamlopt compilation flags
OCAMLOPTFLAGS = -inline 20

OCAMLDEP = $(CAML_PREFIX)/bin/ocamldep
OCAMLLEX = $(CAML_PREFIX)/bin/ocamllex.opt
OCAMLYACC = $(CAML_PREFIX)/bin/ocamlyacc
OCAMLDOC = $(CAML_PREFIX)/bin/ocamldoc
OCAMLMKTOP = $(CAML_PREFIX)/bin/ocamlmktop

CAMLIDL = $(CAMLIDL_PREFIX)/bin/camlidl

LATEX=latex
DVIPDF=dvipdf
MAKEINDEX=makeindex
TEXI2DVI=texi2dvi
TEXI2HTML=texi2html

FLEX=flex
BISON=bison

